#!/bin/bash
#PBS -l select=1:ncpus=64:mpiprocs=64:mem=10GB
#PBS -l walltime=05:00:00
#PBS -q short_cpuQ
#PBS -N 8DFN_nvt_npt
#PBS -o logs/step1_out
#PBS -e logs/step1_err

module load gromacs-2021.4
export OMP_NUM_THREADS=1
cd $PBS_O_WORKDIR

for run in 8DFN_full 8DFN_half 7SI9_full 7SI9_half
do
    cd ../$run

    ############################################################################ EQUILIBRATION
    ##### NVT
    gmx grompp -f ../params/nvt.mdp -c 1_EM/em.gro -r 1_EM/em.gro -p 0_input/topol.top -o 2_NVT/nvt.tpr
    mpirun -np 64 gmx_mpi mdrun -v -deffnm 2_NVT/nvt
    echo "17" | gmx energy -f 2_NVT/nvt.edr -o 2_NVT/temperature.xvg

    ##### NPT
    gmx grompp -f ../params/npt.mdp -c 2_NVT/nvt.gro -r 2_NVT/nvt.gro -t 2_NVT/nvt.cpt -p 0_input/topol.top -o 3_NPT/npt.tpr
    mpirun -np 64 gmx_mpi mdrun -v -deffnm 3_NPT/npt
    echo "19" | gmx energy -f 3_NPT/npt.edr -o 3_NPT/pressure.xvg
    echo "25" | gmx energy -f 3_NPT/npt.edr -o 3_NPT/density.xvg

    ############################################################################ MD
    ##### TPR preparation
    gmx grompp -f ../params/md.mdp -c 3_NPT/npt.gro -t 3_NPT/npt.cpt -p 0_input/topol.top -o 4_MD/md_plain.tpr

done
