#!/bin/bash
#PBS -l select=1:ncpus=32:mpiprocs=32:mem=10GB
#PBS -l walltime=05:00:00
#PBS -q short_cpuQ
#PBS -N 8DFN_em
#PBS -o logs/step0_out
#PBS -e logs/step0_err

module load gromacs-2021.4
export OMP_NUM_THREADS=1
cd $PBS_O_WORKDIR

mkdir logs

for run in 8DFN_full 8DFN_half 7SI9_full 7SI9_half
do
    cd ../$run

    ############################################################################ ENERGY MINIMIZATION
    mkdir 1_EM 2_NVT 3_NPT 4_MD

    gmx grompp -f ../params/minim.mdp -c 0_input/input.gro -p 0_input/topol.top -o 1_EM/em.tpr
    mpirun -np 32 gmx_mpi mdrun -v -deffnm 1_EM/em

    echo "11" | gmx energy -f 1_EM/em.edr -o 1_EM/potential.xvg
done
